---
title: "Plot_in_R"
author: "Yanjun Sun"
date: "6/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# the Goal of this file is to take advantage of ggplot in R to generate plot from MATLAB data

## setup
```{r setup, message = FALSE, warning = FALSE, results = 'hide'}
#search required packages, install them if missing
pkgs_needed = c("dplyr", "ggplot2", "R.matlab", "rhdf5", "tidyr", "BiocManager")
letsinstall = setdiff(pkgs_needed, installed.packages()) 
if (length(letsinstall) > 0) {
  BiocManager::install(letsinstall)
}

#load required packages
library("dplyr")
library("ggplot2")
library("R.matlab")
library("tidyr")
library("BiocManager")
library("rhdf5")
```

## Load data from MATLAB and tranform it into data frame
```{r}
#load .mat file to R and change it to data frame
mat_data <- readMat("Test_Saline.mat") #can only read MAT v7 file and below
mat_data <- h5read("Test_Saline.mat", "corr_LR_saline_pc") # can read MAT v7.3 file, but need to specify var name

r_data <- data.frame(mat_data)

#rename and transform
r_data <- dplyr::rename(r_data, Baseline1 = X1,  Baseline2 = X2, Test1 = X3, Test2 = X4)
my_data <- gather(r_data, Baseline1, Baseline2, Test1, Test2, key = "condition", value = "correlation")
head(my_data)
```

## Generate violin or plots
```{r fig.width = 5, fig.height = 5}
#make an violin plot
ggplot(my_data, aes(x = condition, y = correlation)) + 
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(aes(color = condition), alpha = 0.25, width = 0.2, height = 0)

#make a box plot
ggplot(my_data, aes(x = condition, y = correlation)) + 
  geom_boxplot() +
  geom_jitter(aes(color = condition), alpha = 0.25, width = 0.2, height = 0)
```

## Generate histogram plots
```{r}
#make a histogram of whole data
ggplot(my_data, aes(x = correlation)) +
  geom_histogram(bins = 50)

#make a histogram with facet
my_data2 <- select(my_data, correlation) #select specific data using dplyr::select
ggplot(my_data, aes(x = correlation, fill = condition)) +
  geom_histogram(data = my_data2, bins = 40, fill = "grey", alpha = 0.5) +
  geom_histogram(bins = 40) + 
  facet_wrap(~ condition, ncol = 2)

```

## Generate eCDF plots
```{r}
ggplot(my_data, aes(x = correlation, color = condition)) + 
  stat_ecdf(geom = "step", size = 1) +
  facet_wrap(~ condition, ncol = 2) +
  ylab("Cumulative proportion")

```

## Statistic tests
```{r}
x = dplyr::filter(my_data, condition == "Baseline2")
y = dplyr::filter(my_data, condition == "Test1")
stat_test = t.test(x$correlation, y$correlation, paired = TRUE, alternative = "two.sided")
stat_test

```